<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="sk">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="Content-Language" content="sk" />

	<meta name="robots" content="{$robots}" n:ifset="$robots">

	<title>{block #title}{/block} :: Nette</title>

	<link type="image/png" href="{$basePath}/images/favicon.ico" rel="shortcut icon" />
	<link type="image/png" href="{$basePath}/images/favicon.ico" rel="icon" />

	<link type="text/css" href="{$basePath}/css/site.css" rel="stylesheet" media="screen" />
	<script type="text/javascript" src="{$basePath}/js/jquery.js"></script>
	<script type="text/javascript" src="{$basePath}/js/jquery.nette.js"></script>
</head>

<body><!-- global -->
	{include menu.phtml}
	<div id="flashes" n:snippet="flashMessage">
	<div class="flash {$flash->type}" n:foreach="$flashes as $flash">{!$flash->message}</div>
	</div>
	<div id="content">
		@{include #content}
	</div>
</body>
</html>